"""tz-aware timestamps and unique latest-progress index

Revision ID: 0003be688fd1
Revises: 71b9eea6dfa1
Create Date: 2026-06-11 19:24:21.288563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003be688fd1'
down_revision: Union[str, Sequence[str], None] = '71b9eea6dfa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Collapse any pre-existing duplicate "latest" rows so the unique index below
    # can be created. Keep the highest-id latest row per (user, document); demote
    # the rest. (The DateTime->DateTime(timezone=True) model change is a no-op at
    # SQLite's storage layer, so no column DDL is emitted here.)
    op.execute(
        """
        UPDATE reading_progress
        SET is_latest = 0
        WHERE is_latest = 1
          AND id NOT IN (
            SELECT MAX(id) FROM reading_progress
            WHERE is_latest = 1
            GROUP BY kosync_user_id, document
          )
        """
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_index('uq_reading_progress_latest', ['kosync_user_id', 'document'], unique=True, sqlite_where=sa.text('is_latest = 1'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_index('uq_reading_progress_latest', sqlite_where=sa.text('is_latest = 1'))

    # ### end Alembic commands ###
