"""baseline schema

Revision ID: 1fba6086467b
Revises: 
Create Date: 2026-05-28 20:34:10.048376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fba6086467b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abs_library_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abs_item_id', sa.String(length=255), nullable=False),
    sa.Column('library_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('ebook_filename', sa.String(length=500), nullable=True),
    sa.Column('ebook_format', sa.String(length=20), nullable=True),
    sa.Column('audio_file_count', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Float(), nullable=False),
    sa.Column('abs_updated_at', sa.DateTime(), nullable=True),
    sa.Column('raw_metadata', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abs_library_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abs_library_items_abs_item_id'), ['abs_item_id'], unique=True)

    op.create_table('ebook_metadata_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('file_mtime', sa.Float(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ebook_metadata_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ebook_metadata_cache_path'), ['path'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('alignment_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abs_item_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('audio_cache_dir', sa.String(length=1000), nullable=True),
    sa.Column('ebook_cache_path', sa.String(length=1000), nullable=True),
    sa.Column('sync_map_path', sa.String(length=1000), nullable=True),
    sa.Column('paragraph_count', sa.Integer(), nullable=True),
    sa.Column('fragment_count', sa.Integer(), nullable=True),
    sa.Column('audio_offset_seconds', sa.Float(), nullable=True),
    sa.Column('ebook_path', sa.String(length=1000), nullable=True),
    sa.Column('ebook_source', sa.String(length=20), nullable=True),
    sa.Column('ebook_source_ref', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['abs_item_id'], ['abs_library_items.abs_item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alignment_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alignment_jobs_abs_item_id'), ['abs_item_id'], unique=False)

    op.create_table('kosync_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kosync_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kosync_users_username'), ['username'], unique=True)

    op.create_table('abs_ebook_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('abs_item_id', sa.String(length=255), nullable=False),
    sa.Column('abs_title', sa.String(length=500), nullable=False),
    sa.Column('abs_author', sa.String(length=500), nullable=True),
    sa.Column('ebook_path', sa.String(length=1000), nullable=True),
    sa.Column('ebook_filename', sa.String(length=500), nullable=True),
    sa.Column('ebook_source', sa.String(length=20), server_default='local', nullable=False),
    sa.Column('ebook_source_ref', sa.String(length=1000), nullable=True),
    sa.Column('kosync_document', sa.String(length=64), nullable=True),
    sa.Column('alignment_job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alignment_job_id'], ['alignment_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abs_ebook_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abs_ebook_mappings_abs_item_id'), ['abs_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_abs_ebook_mappings_alignment_job_id'), ['alignment_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_abs_ebook_mappings_kosync_document'), ['kosync_document'], unique=False)
        batch_op.create_index(batch_op.f('ix_abs_ebook_mappings_user_id'), ['user_id'], unique=False)

    op.create_table('reading_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kosync_user_id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(length=500), nullable=False),
    sa.Column('progress', sa.String(length=1000), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('device', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('authors', sa.String(length=500), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kosync_user_id'], ['kosync_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_progress_document'), ['document'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_progress_kosync_user_id'), ['kosync_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_progress_kosync_user_id'))
        batch_op.drop_index(batch_op.f('ix_reading_progress_document'))

    op.drop_table('reading_progress')
    with op.batch_alter_table('abs_ebook_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abs_ebook_mappings_user_id'))
        batch_op.drop_index(batch_op.f('ix_abs_ebook_mappings_kosync_document'))
        batch_op.drop_index(batch_op.f('ix_abs_ebook_mappings_alignment_job_id'))
        batch_op.drop_index(batch_op.f('ix_abs_ebook_mappings_abs_item_id'))

    op.drop_table('abs_ebook_mappings')
    with op.batch_alter_table('kosync_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kosync_users_username'))

    op.drop_table('kosync_users')
    with op.batch_alter_table('alignment_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alignment_jobs_abs_item_id'))

    op.drop_table('alignment_jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('ebook_metadata_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ebook_metadata_cache_path'))

    op.drop_table('ebook_metadata_cache')
    with op.batch_alter_table('abs_library_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abs_library_items_abs_item_id'))

    op.drop_table('abs_library_items')
    # ### end Alembic commands ###
