"""add abs_synced_at to reading_progress

Revision ID: 71b9eea6dfa1
Revises: a3b1326ad413
Create Date: 2026-06-04 13:30:48.041180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b9eea6dfa1'
down_revision: Union[str, Sequence[str], None] = 'a3b1326ad413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abs_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_column('abs_synced_at')

    # ### end Alembic commands ###
