"""add created_by_user_id to alignment_jobs

Revision ID: 95dcc26d3abc
Revises: 1fba6086467b
Create Date: 2026-05-28 20:34:21.871627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95dcc26d3abc'
down_revision: Union[str, Sequence[str], None] = '1fba6086467b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alignment_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_alignment_jobs_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_alignment_jobs_created_by_user_id_users', 'users', ['created_by_user_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alignment_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_alignment_jobs_created_by_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alignment_jobs_created_by_user_id'))
        batch_op.drop_column('created_by_user_id')

    # ### end Alembic commands ###
