"""add abs sync status to reading_progress

Revision ID: a3b1326ad413
Revises: a3f2e1d4c5b6
Create Date: 2026-05-30 09:27:47.023229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b1326ad413'
down_revision: Union[str, Sequence[str], None] = 'a3f2e1d4c5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abs_synced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('abs_sync_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_column('abs_sync_error')
        batch_op.drop_column('abs_synced')

    # ### end Alembic commands ###
